name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            git clone --depth 1 git@github.com:codante-io/changelog.git /var/www/codante-changelog

            cd /var/www/codante-changelog
            npm install
            npm run build
            pm2 restart codante-changelog
